### ISSUE TITLE
Not working with imageSource

### ISSUE THREAD

**Issue by davecoffin** [EddyVerbruggen/nativescript-ocr#6]
Any idea whats going on here?
The error I get is:

```
Argument of type '{ image: ImageSource; }' is not assignable to parameter of type 'RetrieveTextOptions'.
  Types of property 'image' are incompatible.
    Type 'ImageSource' is not assignable to type 'string'.
```

```
        let img = imageSource.fromFile('~/ocrtest.png');

        ocr.retrieveText({
            image: img
        }).then(result => {
                dialogs.alert({
                    title: "Scan OK",
                    message: result.text,
                    okButtonText: "Sweet"
                });
        }, error => {
            dialogs.alert({
                title: "Scan NOT OK",
                message: error,
                okButtonText: "Mmkay"
            });
        });
```

**Comment by davecoffin** [comment]
@EddyVerbruggen any ideas on this?

**Comment by EddyVerbruggen** [comment]
Sorry for the slow reply. Easter and a birthday happened.

I just released 0.2.0 to npm which fixes this TypeScript issue.

**Comment by EddyVerbruggen** [comment]
I'm on {N} 3 at the moment and it seems like `fromFile` is async these days. Can you make sure that is or is not the case for you as well? My code:

```js
        let img: ImageSource = new ImageSource();
        img.fromFile("~/myfile.png").then((success: boolean) => {
          if (success) {
            ocr.retrieveText({
              image: img
            }).then(result => {
              console.log(`Result: ${result.text}`);
            })
          }
        });
```

**Comment by davecoffin** [comment]
Yea, it is async. But I still get the same exact error. My code:
```
let img: ImageSource = new ImageSource();
        
        img.fromFile("~/ocrtest.png").then((success: boolean) => {
            console.log(success);
            if (success) {
                ocr.retrieveText({
                    image: img
                }).then(result => {
                    console.log(`Result: ${result.text}`);
                })
            }
        });
```
The console outputs `true` (result of success), but then dies with the same error when I try to call retreiveText

**Comment by davecoffin** [comment]
I stepped through the plugin and the error occurs at this line:
`var tesseract = G8Tesseract.alloc().initWithLanguage(lang);`

**Comment by EddyVerbruggen** [comment]
Took me a while to get it up and running again, I will post a sample project (hopefully tomorrow).

Main takeaways: add this folder to `App_Resources/iOS/tessdata`, download [this repo](https://github.com/tesseract-ocr/tessdata/tree/3.04.00) and copy all `eng*` files to the `tessdata` folder (assuming you're recognizing `"eng"`).

**Comment by davecoffin** [comment]
Including all the "cube" files? For some reason when I clone the repo it only downloads eng.traineddata, not all the other eng* files. Are those other files necessary?

**Comment by EddyVerbruggen** [comment]
Make sure you use the correct branch (really important). So press the download button at the top right of the repo and copy ALL those eng* files.

If you clone it you'll need to checkout the correct branch afterwards.

**Comment by davecoffin** [comment]
Ok I grabbed those files and added them to both the App_Resources folder and the tessdata folder I had created in xcode based on the instructions noted in the readme, but it still crashes my app. I will patiently await your sample project, thanks!

**Comment by EddyVerbruggen** [comment]
The weird thing is I never have a crash, even if I leave out the tessdata folder (it jsut complains in the log Tesseract hasn't been configured properly). So I'm not entirely sure your crash will be fixed by an example that "works on my machine". Anyway, we'll soon find out 😉

**Comment by davecoffin** [comment]
What version of Nativescript are you on? And Xcode? Thats the only thing I can think of

**Comment by davecoffin** [comment]
I randomly removed my ios platform to address a different issue and added it back, and it works! Amazing! Eddy you rock.

**Comment by EddyVerbruggen** [comment]
Sadly removing and re-adding the platform folders is sometimes required. Glad that worked for you!

I'm in the process of adding some small features to this plugin and will release an update (with the demo project) soon.
